services:
  app:
    image: ${IMAGE_NAME}
    env_file: .env
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:17
    container_name: jobsfoundry_postgres
    environment:
      POSTGRES_DB: jobsfoundry
      POSTGRES_USER: jobsfoundry
      POSTGRES_PASSWORD: jobsfoundry
    ports:
      - "5432:5432"
    volumes:
      - ./db/data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: jobsfoundry_redis
    restart: always

